basePath: /
definitions:
  handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handler.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  handler.StandardResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  handler.TokenResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Authentication service.
  title: Auth Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with username and password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.StandardResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.StandardResponse'
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with username, email and password
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.StandardResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.StandardResponse'
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
