python:
  type: "script"
  build: ""
  run: "python"

javascript:
  type: "script"
  build: ""
  run: "node"

c++:
  type: "compile"
  build: "g++ *.cpp -o main"
  run: "./main"

c:
  type: "compile"
  build: "gcc *.c -o main"
  run: "./main"

go:
  type: "compile"
  build: "go build -ldflags='-s -w' -gcflags='all=-N -l' -o main *.go"
  run: "./main"

assembler:
  type: "compile"
  build: >
    bash -c 'for f in *.asm; do nasm -f elf32 "$f" -o "${f%.asm}.o"; done 
    && gcc -m32 -c /include/macro.c -o __macro__.o 
    && gcc -m32 -static -no-pie *.o -o main'
  run: "./main"

sql:
  type: "script"
  build: ""
  run: "sqlite3 ':memory:'"